---
- hosts: localhost
  tasks:
  - name: Create Docker Image Using our war file
    command: docker build -t dhanvantari-image .
    args:
      chdir: /opt/k8s

  - name: Tag the image
    command: docker tag dhanvantari-image dhanvantarisoftware/dhanvantari-image

  - name: Push the image into our DockerHub registry
    command: docker push dhanvantarisoftware/dhanvantari-image

  - name: Removing Docker images from Ansible server
    command: docker rmi -f dhanvantari-image dhanvantarisoftware/dhanvantari-image
    ignore_errors: yes